<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.gitee.swsk33</groupId>
		<artifactId>git-document-parent</artifactId>
		<version>3.2.0</version>
	</parent>
	<artifactId>git-document-app</artifactId>
	<name>GitDocument App</name>
	<description>GitDocument - 入口启动模块</description>

	<dependencies>
		<dependency>
			<groupId>com.gitee.swsk33</groupId>
			<artifactId>git-document-common</artifactId>
		</dependency>
		<dependency>
			<groupId>com.gitee.swsk33</groupId>
			<artifactId>git-document-system</artifactId>
		</dependency>
		<dependency>
			<groupId>com.gitee.swsk33</groupId>
			<artifactId>git-document-git</artifactId>
		</dependency>
		<dependency>
			<groupId>com.gitee.swsk33</groupId>
			<artifactId>git-document-auth</artifactId>
		</dependency>
		<dependency>
			<groupId>com.gitee.swsk33</groupId>
			<artifactId>git-document-content</artifactId>
		</dependency>
		<dependency>
			<groupId>com.gitee.swsk33</groupId>
			<artifactId>git-document-ssh</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webmvc</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-jdbc</artifactId>
		</dependency>
		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>cn.dev33</groupId>
			<artifactId>sa-token-redis-jackson</artifactId>
		</dependency>
		<dependency>
			<groupId>org.redisson</groupId>
			<artifactId>redisson-spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.lionsoul</groupId>
			<artifactId>ip2region</artifactId>
		</dependency>
		<dependency>
			<groupId>io.github.swsk33</groupId>
			<artifactId>sql-initialize-spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>io.lettuce</groupId>
			<artifactId>lettuce-core</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<excludes>
						<exclude>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
						</exclude>
						<exclude>
							<groupId>com.mybatis-flex</groupId>
							<artifactId>mybatis-flex-processor</artifactId>
						</exclude>
					</excludes>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>