# 服务端配置
server:
  port: 8800
  tomcat:
    max-http-form-post-size: 20MB

# 日志配置
logging:
  file:
    name: "log/git-doc.log"
  level:
    root: info

spring:
  # JSON配置
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
  # 邮件配置
  mail:
    default-encoding: UTF-8
    host: "邮箱smtp"
    username: "邮箱"
    password: "授权码"
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: "javax.net.ssl.SSLSocketFactory"
            port: 465
          starttls:
            enable: true
            required: true
  # 请求大小
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  # MySQL数据库
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/git_doc?serverTimezone=GMT%2B8"
    username: "用户名"
    password: "密码"
  data:
    # Redis
    redis:
      host: 127.0.0.1
      port: 6379
      password: "密码"
  # RabbitMQ
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: "用户名"
    password: "密码"

# Sa-Token配置
sa-token:
  is-concurrent: true
  is-share: false
  timeout: -1
  token-name: gitdoc-satoken
  token-style: simple-uuid

# git-document配置
com:
  gitee:
    swsk33:
      git-doc:
        repo-path: "/git-doc"
        host-port: 23
        allow-public: true
        organization-name: "组织名"
