services:
  # GitDocument
  git-doc:
    image: swsk33/git-document
    ports:
      - 2333:2333
      - 80:80
      - 443:443
    environment:
      - GITDOC_DB_HOST=postgre
      - GITDOC_REDIS_HOST=redis
      # 邮箱配置（需要自己填一下）
      - GITDOC_MAIL_SMTP_HOST=smtp.163.com
      - GITDOC_MAIL_USER=你的邮箱
      - GITDOC_MAIL_PASSKEY=授权码
      # SSH广播端口（映射的宿主机的SSH端口）
      - GITDOC_ADVERTISED_SSH_PORT=2333
      # 设定延迟启动时长（秒）以等待数据库和消息队列启动完成后再启动
      - DELAY_START=3
    volumes:
      - nginx-config:/etc/nginx
      - git-repository:/git-doc
      - image:/app/images
    links:
      - postgre
      - redis
    depends_on:
      - postgre
      - redis
  # Redis
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
  # PostgreSQL
  postgre:
    image: postgres:alpine
    volumes:
      - postgre-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456

volumes:
  postgre-data:
  redis-data:
  nginx-config:
  git-repository:
  image:
