<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.gitee.swsk33</groupId>
		<artifactId>git-document-parent</artifactId>
		<version>3.2.0</version>
	</parent>
	<artifactId>git-document-auth</artifactId>
	<name>GitDocument Auth</name>
	<description>GitDocument - 用户与认证模块</description>

	<dependencies>
		<!-- 内部模块 -->
		<dependency>
			<groupId>com.gitee.swsk33</groupId>
			<artifactId>git-document-common</artifactId>
		</dependency>
		<dependency>
			<groupId>com.gitee.swsk33</groupId>
			<artifactId>git-document-system</artifactId>
		</dependency>

		<!-- Spring Boot Web -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webmvc</artifactId>
		</dependency>

		<!-- Spring Boot 切面 -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-aspectj</artifactId>
		</dependency>

		<!-- Sa-Token 认证鉴权 -->
		<dependency>
			<groupId>cn.dev33</groupId>
			<artifactId>sa-token-spring-boot4-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>cn.dev33</groupId>
			<artifactId>sa-token-spring-aop</artifactId>
		</dependency>

		<!-- BCrypt 加密 -->
		<dependency>
			<groupId>org.mindrot</groupId>
			<artifactId>jbcrypt</artifactId>
		</dependency>

		<!-- MyBatis-Flex 增强框架 -->
		<dependency>
			<groupId>com.mybatis-flex</groupId>
			<artifactId>mybatis-flex-spring-boot4-starter</artifactId>
		</dependency>

		<!-- 验证码框架 -->
		<dependency>
			<groupId>io.github.swsk33</groupId>
			<artifactId>code-post-spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>io.lettuce</groupId>
			<artifactId>lettuce-core</artifactId>
		</dependency>

		<!-- MINA SSHD -->
		<dependency>
			<groupId>org.apache.sshd</groupId>
			<artifactId>sshd-core</artifactId>
		</dependency>

		<!-- IP 查询 -->
		<dependency>
			<groupId>org.lionsoul</groupId>
			<artifactId>ip2region</artifactId>
		</dependency>

		<!-- Hutool 实用类 -->
		<dependency>
			<groupId>cn.hutool</groupId>
			<artifactId>hutool-core</artifactId>
		</dependency>
	</dependencies>
</project>