<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>4.1.0</version>
		<relativePath/>
	</parent>
	<groupId>com.gitee.swsk33</groupId>
	<artifactId>git-document-parent</artifactId>
	<version>3.2.0</version>
	<packaging>pom</packaging>
	<name>GitDocument Parent</name>
	<description>基于Git版本管理工具的轻便的文档管理系统，使用Git管理Markdown文档，该模块为顶层父模块</description>

	<modules>
		<module>common</module>
		<module>system</module>
		<module>git</module>
		<module>auth</module>
		<module>content</module>
		<module>app</module>
		<module>ssh</module>
	</modules>

	<properties>
		<!-- 基本信息 -->
		<java.version>21</java.version>
		<maven.compiler.release>${java.version}</maven.compiler.release>
		<maven.compiler.parameters>true</maven.compiler.parameters>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<skipTests>true</skipTests>
		<!-- 部分版本管理 -->
		<sa-token.version>1.45.0</sa-token.version>
		<mybatis-flex.version>1.11.7</mybatis-flex.version>
	</properties>

	<dependencies>
		<!-- Lombok 注解 -->
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<scope>provided</scope>
		</dependency>
	</dependencies>

	<dependencyManagement>
		<dependencies>
			<!-- 项目子模块版本管理 -->
			<dependency>
				<groupId>com.gitee.swsk33</groupId>
				<artifactId>git-document-common</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.gitee.swsk33</groupId>
				<artifactId>git-document-system</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.gitee.swsk33</groupId>
				<artifactId>git-document-git</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.gitee.swsk33</groupId>
				<artifactId>git-document-auth</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.gitee.swsk33</groupId>
				<artifactId>git-document-content</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.gitee.swsk33</groupId>
				<artifactId>git-document-ssh</artifactId>
				<version>${project.version}</version>
			</dependency>

			<!-- Lombok 注解 -->
			<dependency>
				<groupId>org.projectlombok</groupId>
				<artifactId>lombok</artifactId>
				<version>1.18.46</version>
			</dependency>

			<!-- Reactor 反应式编程 -->
			<dependency>
				<groupId>io.projectreactor</groupId>
				<artifactId>reactor-bom</artifactId>
				<version>2025.0.6</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>

			<!-- Hutool 实用工具 -->
			<dependency>
				<groupId>cn.hutool</groupId>
				<artifactId>hutool-bom</artifactId>
				<version>5.8.46</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>

			<!-- MyBatis-Flex 框架相关 -->
			<dependency>
				<groupId>com.mybatis-flex</groupId>
				<artifactId>mybatis-flex-spring-boot4-starter</artifactId>
				<version>${mybatis-flex.version}</version>
			</dependency>
			<dependency>
				<groupId>com.mybatis-flex</groupId>
				<artifactId>mybatis-flex-processor</artifactId>
				<version>${mybatis-flex.version}</version>
			</dependency>
			<dependency>
				<groupId>com.mybatis-flex</groupId>
				<artifactId>mybatis-flex-core</artifactId>
				<version>${mybatis-flex.version}</version>
			</dependency>

			<!-- Sa-Token框架相关 -->
			<dependency>
				<groupId>cn.dev33</groupId>
				<artifactId>sa-token-spring-boot4-starter</artifactId>
				<version>${sa-token.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.dev33</groupId>
				<artifactId>sa-token-spring-aop</artifactId>
				<version>${sa-token.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.dev33</groupId>
				<artifactId>sa-token-redis-jackson</artifactId>
				<version>${sa-token.version}</version>
			</dependency>

			<!-- BCrypt 加密 -->
			<dependency>
				<groupId>org.mindrot</groupId>
				<artifactId>jbcrypt</artifactId>
				<version>0.4</version>
			</dependency>

			<!-- Redisson -->
			<dependency>
				<groupId>org.redisson</groupId>
				<artifactId>redisson-spring-boot-starter</artifactId>
				<version>4.5.0</version>
			</dependency>

			<!-- MINA SSHD 框架 -->
			<dependency>
				<groupId>org.apache.sshd</groupId>
				<artifactId>sshd-core</artifactId>
				<version>2.18.0</version>
			</dependency>

			<!-- JGit 客户端 -->
			<dependency>
				<groupId>org.eclipse.jgit</groupId>
				<artifactId>org.eclipse.jgit</artifactId>
				<version>7.7.0.202606012155-r</version>
			</dependency>

			<!-- IP 查询框架 -->
			<dependency>
				<groupId>org.lionsoul</groupId>
				<artifactId>ip2region</artifactId>
				<version>3.3.7</version>
			</dependency>

			<!-- 数据库自动初始化框架 -->
			<dependency>
				<groupId>io.github.swsk33</groupId>
				<artifactId>sql-initialize-spring-boot-starter</artifactId>
				<version>3.0.1</version>
			</dependency>

			<!-- 邮件验证码框架相关 -->
			<dependency>
				<groupId>io.github.swsk33</groupId>
				<artifactId>code-post-spring-boot-starter</artifactId>
				<version>2.0.1</version>
			</dependency>
			<dependency>
				<groupId>io.lettuce</groupId>
				<artifactId>lettuce-core</artifactId>
				<version>7.6.0.RELEASE</version>
			</dependency>

			<!-- 文件上传框架 -->
			<dependency>
				<groupId>io.github.swsk33</groupId>
				<artifactId>file-lift-spring-boot-starter</artifactId>
				<version>2.0.2</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<!-- 编译插件 -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<annotationProcessorPaths>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
							<version>${lombok.version}</version>
						</path>

						<path>
							<groupId>com.mybatis-flex</groupId>
							<artifactId>mybatis-flex-processor</artifactId>
							<version>${mybatis-flex.version}</version>
						</path>
					</annotationProcessorPaths>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>