<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.gitee.swsk33</groupId>
		<artifactId>git-document-parent</artifactId>
		<version>3.2.0</version>
	</parent>
	<artifactId>git-document-ssh</artifactId>
	<name>GitDocument SSH</name>
	<description>GitDocument - SSH服务端模块，包含SSH服务端实现、认证、公钥管理、Git接入逻辑</description>

	<dependencies>
		<!-- 内部模块 -->
		<dependency>
			<groupId>com.gitee.swsk33</groupId>
			<artifactId>git-document-common</artifactId>
		</dependency>
		<dependency>
			<groupId>com.gitee.swsk33</groupId>
			<artifactId>git-document-git</artifactId>
		</dependency>

		<!-- Spring Boot 基本模块 -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webmvc</artifactId>
		</dependency>

		<!-- Sa-Token 认证鉴权 -->
		<dependency>
			<groupId>cn.dev33</groupId>
			<artifactId>sa-token-spring-boot4-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>cn.dev33</groupId>
			<artifactId>sa-token-spring-aop</artifactId>
		</dependency>

		<!-- MyBatis-Flex 增强框架 -->
		<dependency>
			<groupId>com.mybatis-flex</groupId>
			<artifactId>mybatis-flex-spring-boot4-starter</artifactId>
		</dependency>

		<!-- SSHD 实现 -->
		<dependency>
			<groupId>org.apache.sshd</groupId>
			<artifactId>sshd-core</artifactId>
		</dependency>
	</dependencies>
</project>